# 12-9-2019

# Tasks

In [1]:
def isprime(n):
    if n==0 or n==1:
        return False
    flag=True
    for i in range(2,int(n**(1/2))+1):
        if n%i==0:
            flag=False
    return flag

tc=int(input())
for t in range(tc):
    n=input('enter a number : ')
    m='0'
    if '6' in n:
        m=n.replace('6','s')
    if '9' in m:
        m=m.replace('9','6')
    if 's' in m:
        m=m.replace('s','9')

    if isprime(int(n)) and isprime(int(n[::-1])) and isprime(int(m)) and isprime(int(m[::-1])):
        print('beminp')
    elif isprime(int(n)) and isprime(int(n[::-1])):
        print("eminp")
    else:
        print('no')

4
enter a number : 11061811
11061811
11816011
11091811
11819011
beminp
enter a number : 13
13
31
0
13
31
eminp
enter a number : 9
9
9
no
enter a number : 1961
1961
1961
no


# Class

# Numpy

In [12]:
import numpy as np
a=[1,2,3,4,5,6]
data=np.array(a)
print(data,type(data))
print(a,type(a))
type(data)

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6] <class 'list'>


numpy.ndarray

In [4]:
data1=np.array([22,33,44,55,66])

In [7]:
print(data1)
data1,a

[22 33 44 55 66]


(array([22, 33, 44, 55, 66]), [1, 2, 3, 4, 5, 6])

In [8]:
data1=np.array([[1,2,3,4,5],[5,4,3,3,2]])  #2D array

In [9]:
data1

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 3, 2]])

In [10]:
type(data1)

numpy.ndarray

In [14]:
data1.shape         #gives count of columns and rows


(2, 5)

In [31]:
data=np.arange(0,100)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [32]:
d=np.arange(0,100,3)
print(d)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [33]:
data1=data.reshape(10,10)       # rearrange with 10 rows and 10 columns
print(data,data1,sep='\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [34]:
data6=np.linspace(0,8,20)
data6

array([0.        , 0.42105263, 0.84210526, 1.26315789, 1.68421053,
       2.10526316, 2.52631579, 2.94736842, 3.36842105, 3.78947368,
       4.21052632, 4.63157895, 5.05263158, 5.47368421, 5.89473684,
       6.31578947, 6.73684211, 7.15789474, 7.57894737, 8.        ])

In [35]:

data7=np.random.randint(0,20,size=(2,4))
data7

array([[ 8, 16, 16,  2],
       [19,  6,  3, 17]])

In [36]:
data8=np.ones((4,3))
data8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
data8=np.ones((4,3),int)
data8

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
data8=np.zeros((4,3),int)
data8

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
data9=np.ones((4,3),int)
data9
np.vstack([data9,data9*10])

array([[ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [40]:
data9=np.ones((4,3),int)
data9
np.hstack([data9,data9*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

#  array operators

In [41]:
n1=np.array([1,2,3,4])
n2=np.array([2,3,4,5])
n1,n2
n1+n2

array([3, 5, 7, 9])

In [42]:
n1-n2


array([-1, -1, -1, -1])

In [43]:
n1*n2

array([ 2,  6, 12, 20])

In [44]:

n1/n2

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [45]:

n1%n2

array([1, 2, 3, 4], dtype=int32)

In [46]:

n1 & n2

array([0, 2, 0, 4], dtype=int32)

In [47]:
n1 | n2

array([3, 3, 7, 5], dtype=int32)

In [48]:
n1.dot(n2)

40

In [50]:
data2=np.array([[1,2,3,4],[2,3,4,5]])
data2.T

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [51]:
data2.min()

1

In [52]:

data2.max()

5

In [55]:
np.sin(data2)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [ 0.90929743,  0.14112001, -0.7568025 , -0.95892427]])

In [54]:

np.sqrt(data2)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.41421356, 1.73205081, 2.        , 2.23606798]])