# 1. Write a Pandas program to change the order of index of a given series.

In [1]:
l={'Name':['Vyshnavi','Srijanya','Keerthi','Usha','Op','Prakesh','Deepika','Haritha','Sirisha'],
  "Roll.no":['515','507','511','547','550','519','530','542','522'],
  'Place':['Kodamanchili','Bhimavaram','Narspur','Tirupati','Narspur','Narspur',None,None,None,],
  'Age':[22,21,23,22,20,19,22,21,23]}

In [7]:
t=['Vyshnavi','Srijanya','Keerthi','Usha','Op','Prakesh','Deepika','Haritha','Sirisha']
import pandas as pd
import numpy as np
df=pd.Series(t)
df=df.reindex([1,4,2,5,3,6,8,7])
df

1    Srijanya
4          Op
2     Keerthi
5     Prakesh
3        Usha
6     Deepika
8     Sirisha
7     Haritha
dtype: object

# 2. Write a Python program to add, subtract, multiple and divide two Pandas
Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [22]:
x=[[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]]
df2=pd.DataFrame(x)
print('addition')
print(df2.iloc[0,:]+df2.iloc[1,:])
print('subtraction')
print(df2.iloc[0,:]-df2.iloc[1,:])
print('multiplication')
print(df2.iloc[0,:]*df2.iloc[1,:])
print('division')
print(df2.iloc[0,:]/df2.iloc[1,:])

addition
0     3
1     7
2    11
3    15
4    19
dtype: int64
subtraction
0    1
1    1
2    1
3    1
4    1
dtype: int64
multiplication
0     2
1    12
2    30
3    56
4    90
dtype: int64
division
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# 3. Write a Python program to convert a Panda module Series to Python list and it&#39;s type

In [30]:
df3=list(df)
df3,type(df3)

(['Srijanya',
  'Op',
  'Keerthi',
  'Prakesh',
  'Usha',
  'Deepika',
  'Sirisha',
  'Haritha'],
 list)

# 4. Write a Pandas program to select the rows where the score is missing, i.e. is NaN

In [54]:
exam_data = {'name': ['Sachin' ,  'Ganguly' ,  'Kohli' ,  'Johnson' ,  'Taylor' ,
 'Waugh' ,  'Yuvraj' ,  'Kambli' ,  'Srinath' ,  'Munaf' ],
 'score' : [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
 'attempts' : [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
 'qualify' : [ 'yes' ,  'no' ,  'yes' ,  'no' ,  'no' ,  'yes' ,  'yes' ,  'no' ,  'no' ,  'yes' ]}
labels = [ 'a' ,  'b' ,  'c' ,  'd' ,  'e' ,  'f' ,  'g' ,  'h' ,  'i' ,  'j' ]
df4=pd.DataFrame(exam_data,index=labels)
df4

name  score  attempts qualify
a   Sachin   12.5         1     yes
b  Ganguly    9.0         3      no
c    Kohli   16.5         2     yes
d  Johnson    NaN         3      no
e   Taylor    9.0         2      no
f    Waugh   20.0         3     yes
g   Yuvraj   14.5         1     yes
h   Kambli    NaN         1      no
i  Srinath    8.0         2      no
j    Munaf   19.0         1     yes

In [55]:
df4.iloc[:,][df4.score.isna()]

name  score  attempts qualify
d  Johnson    NaN         3      no
h   Kambli    NaN         1      no

# 5. Write a Pandas program to create todays date

In [56]:
from datetime import *


# 6.Write a Pandas program to create a Pivot table, by considering Titanic Dataset

# 7.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [62]:
n=np.arange(2,11)
n=n.reshape(3,3)
n

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 8.Illustrate the difference between ravel and flatten by taking considering multidimensional array.

In [68]:
a=n.ravel()
b=n.flatten()
a,b

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [70]:
a[0]=10
n,a

(array([[10,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]), array([10,  3,  4,  5,  6,  7,  8,  9, 10]))

In [71]:
b[0]=20
n,b

(array([[10,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]), array([20,  3,  4,  5,  6,  7,  8,  9, 10]))

 # 9. Create a 3×3 numpy array, find out the Minimum,Maximum values and also their indices accordingly for each axes. Also find out the Statistical methods such as Standard Deviation,Cumulative sum and product.


In [74]:
df9=pd.DataFrame(n)
df9.describe()

0    1     2
count   3.000000  3.0   3.0
mean    7.666667  6.0   7.0
std     2.516611  3.0   3.0
min     5.000000  3.0   4.0
25%     6.500000  4.5   5.5
50%     8.000000  6.0   7.0
75%     9.000000  7.5   8.5
max    10.000000  9.0  10.0

# 10. Illustrate the concept of splitting by taking random positive values and also implementing different stacking methods on them.